
  home.file."~/.config/hypr/hyprland.conf.ee".text =
    ''
    
# #######################################################################################
# AUTOGENERATED HYPR CONFIG.


#exec-once = hyprctl dispatch dpms off;hyprctl dispatch dpms on; hyprlock
#exec-once = hyprlock




# PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
# OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
# #######################################################################################

#autogenerated = 1 # remove this line to remove the warning

# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,1920x1200,auto,auto
#monitor=,780x500,auto,auto
#monitor=,prefered,auto,auto
monitor=eDP-2, disable

###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$fileManager = thunar
$exec_once = launch_once
#$menu = launch_once "DRI_PRIME=1" "wofi" "--show drun"
#$menu = nu -c 'source /home/mxmfrpr/projects/launch_once/launch_once.nu; launch_once "DRI_PRIME=$(cat .config/gputools/DRI_PRIME.txt)" "wofi" "--show drun -Ddrun-disable_prime=true -I"'
$menu = nu -c "DRI_PRIME=$(cat .config/gputools/DRI_PRIME.txt) wofi --show drun -Ddrun-disable_prime=true -I"


exec-once = waybar


#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox


#env = AQ_DRM_DEVICES,/dev/dri/card2 #/dev/dri/card1
#:/dev/dri/card2
env = DRI_PRIME, 2


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 6
    gaps_out = 18

    border_size = 1

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(8363f7ee) rgba(94a9ffee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle

    gaps_workspaces = 150

    snap {
        enabled = true
	monitor_gap = 10

    }

}


xwayland {
    force_zero_scaling = true
}


# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 20

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.99 #0.76
    shadow {
        enabled = false
    }
    #drop_shadow = true
    #shadow_range = 4
    #shadow_render_power = 3
    #col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = false
        size = 6
        passes = 1
        
        vibrancy = 0.6
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
#
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = easeOutSine, 0.23, 1, 0.32, 1
    bezier = easeInQuad, 0.55, 0.085, 0.68, 0.53
    bezier = easeOutQuart, 0.165, 0.84, 0.3, 1
    bezier = easeInOutBack, 0.68, -0.55, 0.265, 1.55
    bezier = easeOutQuint, 0.23, 1, 0.32, 1

    animation = windows, 1, 10, easeOutSine
    animation = windowsOut, 1, 3, easeOutQuart, popin 75%
    animation = border, 1, 3, easeOutSine
    animation = borderangle, 1, 10, default
    animation = fade, 1, 7, easeOutQuart
    animation = workspaces, 1, 5, easeOutQuint
    animation = specialWorkspace, 1, 6, default, slidefadevert -80%
    layerrule = noanim, ^(wofi)$
    layerrule = noanim, ^(rofi)$
    #layerrule = animation fade,^(wofi)$
    #layerrule = animation animation, ^(wofi)$
    #animation = layers, 1, 0.2, default, fadeLayers
    #animation = layers, 1, 2.8, default, popin 80%
    #animation = fadeLayers, 1, 5, easeOutSine
    #animation = fadeLayersOut, 1, 7, easeOutSine
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
    vfr = true
}


#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us,ru,us
    kb_variant = colemak,,
    kb_model =
    kb_options = grp:alt_space_toggle, caps:swapescape, altwin:swap_ctrl_win #custom:swap_ctrl_cmd
    kb_rules =

    follow_mouse = 1

    sensitivity = -1.0 # -1.0 - 1.0, 0 means no modification.
    #accel_profile = custom 20 0 2 14 30 60 60 60 60 60 #
    accel_profile = custom 13 0 0.8 4.5 11.8 17.0 22.0 23.0 28.0 28.0 28.0 28.0 
    touchpad {
        natural_scroll = true
	#scroll_factor = 0.008#35
	scroll_factor = 0.022
        clickfinger_behavior = 1
	drag_lock = true
	tap-to-click = false
	disable_while_typing = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_min_fingers = true
    workspace_swipe_distance = 900
    workspace_swipe_cancel_ratio = 0.3
    workspace_swipe_forever = true
    workspace_swipe_min_speed_to_force = 3
    workspace_swipe_direction_lock = false
}


# Example per-dvice config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = 0.0
}


####################
### KEYBINDINGSS ###
####################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = Super # Sets "Windows" key as main modifier
#$altMod = Super

#bind = SUPER, , exec, "hyprctl dispatch sendshortcut Control,,"
bindr = $altMod Shift, Shift_L, exec, hyprctl dispatch sendshortcut Control,F,activewindow

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, Y, exec, $fileManager
bind = $mainMod, code:94, togglefloating,
bind = $mainMod, D, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod SHIFT, code:94, togglesplit, # dwindle
bind = $mainMod, Space, exec, $menu
bind = $mainMod, f, fullscreen
bind = $mainMod, B, exec, wlogout
bind = $mainMod, K, exec, hyprctl dispatch dpms off;hyprctl dispatch dpms on


# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, n, movefocus, l
bind = $mainMod, o, movefocus, r
bind = $mainMod, i, movefocus, u
bind = $mainMod, e, movefocus, d


bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

bind = $mainMod SHIFT, o, movewindow, r
bind = $mainMod SHIFT, n, movewindow, l
bind = $mainMod SHIFT, i, movewindow, u
bind = $mainMod SHIFT, e, movewindow, d


#bind = $altMod, right, exec, hyprctl dispatch sendshortcut Control, right, activewindow
#bind = $altMod, left, exec, hyprctl dispatch sendshortcut Control, left, activewindow
#bind = $altMod, up, exec, hyprctl dispatch sendshortcut Control, up, activewindow
#bind = $altMod, down, exec, hyprctl dispatch sendshortcut Control, down, activewindow
#bind = $altMod, F, exec, hyprctl dispatch sendshortcut Control, F, activewindow

#bind = $altMod, Return, exec, hyprctl dispatch sendshortcut Control, Return, activewindow

#bind = $altMod, P, exec, hyprctl dispatch sendshortcut Control, P, activewindow




# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic


bind = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_SINK@ 10%+

bind = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_SINK@ 10%-

bind = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_SINK@ toggle



#bind = ,XF86MonBrightnessUp, exec, brightnessctl set +3%

#bind = ,XF86MonBrightnessDown, exec, brightnessctl set 3%-

bind = ,XF86MonBrightnessUp, exec, nu -c "brightnessctl set (([(brightnessctl g) +500] | into int | math sum) * 1.4 | into int)"

bind = ,XF86MonBrightnessDown, exec, nu -c "brightnessctl set ( [ ( [ (( [(brightnessctl g)] | into int | math sum) * 0.71 | into int) -500 ] | math sum) 0] | math max )"


bind =,XF86KbdBrightnessUp, exec, brightnessctl --device=':white:kbd_backlight' set +20%

bind =,XF86KbdBrightnessDown, exec, brightnessctl --device=':white:kbd_backlight' set 20%-

bind =,XF86Search, exec, $menu

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
env=XCURSOR_THEME,Vimix-cursors
cursor {
  enable_hyprcursor = false
}
    '';
 
